<a href="https://colab.research.google.com/github/tenzin67/Blogpage/blob/main/1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [6]:
import numpy as np


In [4]:
import torch
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
reshaped = my_torch.reshape(2,5)
reshaped

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
torch2 = torch.arange(15)
torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
my_torch2 =torch2.reshape(3,5)
my_torch2


tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

MATHS OPERATION IN TENSOR

In [12]:
a = torch.tensor([1.,2.,3.])
b = torch.tensor([4.,5.,6.])
# Tensor Addition
torch.add(a,b)
a+b

#Tensor Subtraction
torch.sub(a,b)
a-b

#Tensor Multiplication
torch.mul(a,b)
a*b

#Tensor Division
torch.div(a,b)
a/b

tensor([0.2500, 0.4000, 0.5000])

LIST HERE

In [8]:
mylist =[[1,2,3,4],[5,6,7,8]]
mylist

[[1, 2, 3, 4], [5, 6, 7, 8]]